spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dastar?serverTimezone=UTC&characterEncoding=UTF-8
    username: danawa
    password: danawa-pass

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/dastar?serverTimezone=UTC&characterEncoding=UTF-8
    user: danawa
    password: danawa-pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

# open-ssl rand -base64 32 로 만든 키 값
# 토이프로젝트라 그냥 공개 dev 환경 access-token, refresh-token 만료시간 1분, 5분
jwt:
  access-token:
    secret-key: QtvtPoR7jzKvMhNz287qdGMarNvORp+lgSELkuD393I=
    expire-time: 60000
  refresh-token:
    secret-key: AMG12t18NLkQTx3SnNTNSUzUnM4SdJZUGG9GZS4DVQY=
    expire-time: 300000
