POST http://localhost:8080/api/v1/comments
Content-Type: application/json

{
  "content": "댓글테스트",
  "postId": 1,
  "memberId": 1
}

###

PUT http://localhost:8080/api/v1/comments
Content-Type: application/json

{
  "content": "댓글테스트",
  "postId": 123123,
  "memberId": 12123
}