POST http://localhost:8080/api/v1/members
Content-Type: application/json

{
  "email": "hong@test.com",
  "password": "hongtest123!",
  "nickname": "조선도적",
  "name": "홍길동"
}

###

PUT http://localhost:8080/api/v1/members
Content-Type: application/json

{
  "nickname": "조선해적",
  "name": "김길동",
  "password": null,
  "profileImage": null
}