name: build

# develop 브랜치로 pull request가 opened 될 때만 실행
on:
  pull_request:
    branches: [ develop ]
    types: [ opened ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    # ubuntu-latest 환경에서 실행
    runs-on: ubuntu-latest
    steps:
      # checkout action을 통해 소스코드를 가져옴
      - name: Checkout
        uses: actions/checkout@v3

      # java 17을 설치
      - name: install java17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # gradle 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle 빌드
      - name: Build Test
        run: ./gradlew build