name: deploy

# master 브랜치로 pull request가 opened 될 때만 실행
on:
  pull_request:
    branches: [ test ]
    types: [ opened ]

# 환경변수
env:
  CONTAINER_REGISTRY: ghcr.io

jobs:
  deploy:
    # ubuntu-latest 환경에서 실행
    runs-on: ubuntu-latest
    steps:
      # checkout action을 통해 소스코드를 가져옴
      - name: Checkout
        uses: actions/checkout@v3

      # java 17을 설치
      - name: install java17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # gradle 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle 빌드
      - name: Build
        run: ./gradlew build

      # extract_version.sh 실행하여 jar파일 버전 추출
      - name: Extract version
        id: get_version
        run: |
          chmod +x ./shell/extract_version.sh
          VERSION=$(./shell/extract_version.sh)
          echo "::set-output name=VERSION::$VERSION"

      # 도커 세팅
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ghcr.io 로그인
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # pull request가 아닐 때만 도커 빌드 및 푸시
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: VERSION=${{ steps.get_version.outputs.VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.CONTAINER_REGISTRY }}/dastargram:${{ steps.get_version.outputs.VERSION }}